from enum import StrEnum


class ChatIntent(StrEnum):
    GENERAL_CHAT = "GENERAL_CHAT"
    CONTRACT = "CONTRACT"
    CONTRACT_DEPOSIT = "CONTRACT_DEPOSIT"
    CONTRACT_PAYMENT = "CONTRACT_PAYMENT"
    SCHEDULE = "SCHEDULE"
    FINANCE_SUMMARY = "FINANCE_SUMMARY"
    EXPENSE_SIMULATION = "EXPENSE_SIMULATION"
    FOLLOW_UP = "FOLLOW_UP"
    NEEDS_CLARIFICATION = "NEEDS_CLARIFICATION"
    UNKNOWN = "UNKNOWN"
