from enum import StrEnum


class ChatIntent(StrEnum):
    CONTRACT = "CONTRACT"
    CONTRACT_PAYMENT = "CONTRACT_PAYMENT"
    SCHEDULE = "SCHEDULE"
    FINANCE_SUMMARY = "FINANCE_SUMMARY"
    EXPENSE_SIMULATION = "EXPENSE_SIMULATION"
    UNKNOWN = "UNKNOWN"
